### ISSUE TITLE
abusehelper.core.shadowservermail: Crash on incomplete data & Python 2.6

### ISSUE THREAD

**Issue by ghost** [abusesa/abusehelper#2]
@svimes-work reported that `abusehelper.core.shadowservermail` crashes on a some mails it's supposed to be able to handle:

```
2015-12-08 09:45:31Z shadowservermail[74486] INFO Handling mail u'...' from u'...'
2015-12-08 09:45:31Z shadowservermail[74486] INFO Opening a ZIP attachment
2015-12-08 09:45:31Z shadowservermail[74486] INFO Parsing CSV data from the ZIP attachment
2015-12-08 09:46:03Z shadowservermail[74486] CRITICAL Traceback (most recent call last):
2015-12-08 09:46:03Z shadowservermail[74486] CRITICAL   File "abusehelper/core/bot.py", line 302, in execute
2015-12-08 09:46:03Z shadowservermail[74486] CRITICAL     return self.run()
...
2015-12-08 09:46:03Z shadowservermail[74486] CRITICAL   File "abusehelper/core/utils.py", line 129, in csv_to_events
2015-12-08 09:46:03Z shadowservermail[74486] CRITICAL     for row in _csv_reader(fileobj, charset=charset, delimiter=delimiter):
2015-12-08 09:46:03Z shadowservermail[74486] CRITICAL   File "abusehelper/core/utils.py", line 123, in _csv_reader
2015-12-08 09:46:03Z shadowservermail[74486] CRITICAL     for row in csv.reader(lines, **keys):
2015-12-08 09:46:03Z shadowservermail[74486] CRITICAL Error: newline inside string
```

Turns out the crashing mail contains a compressed .csv.zip attachment. The uncompressed data is incomplete, ending in the middle of a quoted string. The URL embedded in the mail returned the same incomplete data. Here's a similar but artificial example - note that the data just ends mid-line, there's no trailing newline or anything:

```
"timestamp","ip","hostname"
"2015-12-08 09:51:14","192.0.2.15","www.example.com"
"2015-12-08 09:52:30","198.51.100.3","mail.examp
```

It seems that the crash is triggered only when running the bot against such data using Python 2.6. Python 2.7 survives just fine.

**Comment by ghost** [comment]
A related issue with Python 2.6's `csv` module: https://bugs.python.org/issue16013
