### ISSUE TITLE
Yielding roomreader improperly leads to the crash of startupbot and losing track of other bot PIDs

### ISSUE THREAD

**Issue by ghost** [abusesa/abusehelper#46]
It seems that when yielding bot in a following manner:

``` python
from abusehelper.core.startup import Bot
from abusehelper.tools.roomreader import main as roomreader

...

bot = Bot([bot configurations])
yield bot("roomreader", roomreader)
```

Leads to startupbot to crash with following traceback:

```
2016-04-18 10:18:24Z startup[2824] CRITICAL Traceback (most recent call last):
2016-04-18 10:18:24Z startup[2824] CRITICAL   File "/usr/lib/python2.6/site-packages/abusehelper/core/bot.py", line 308, in execute
2016-04-18 10:18:24Z startup[2824] CRITICAL     return self.run()
2016-04-18 10:18:24Z startup[2824] CRITICAL   File "/usr/lib/python2.6/site-packages/abusehelper/core/startup.py", line 295, in run
2016-04-18 10:18:24Z startup[2824] CRITICAL     return idiokit.main_loop(self.configs() | self.read() | self.main())
2016-04-18 10:18:24Z startup[2824] CRITICAL   File "/usr/lib/python2.6/site-packages/idiokit/idiokit.py", line 298, in _next
2016-04-18 10:18:24Z startup[2824] CRITICAL     next = require_stream(self._gen.send(peel_args(args)))
2016-04-18 10:18:24Z startup[2824] CRITICAL   File "/usr/lib/python2.6/site-packages/abusehelper/core/startup.py", line 285, in main
2016-04-18 10:18:24Z startup[2824] CRITICAL     self._processes[conf] = self._launch(conf), strategy
2016-04-18 10:18:24Z startup[2824] CRITICAL   File "/usr/lib/python2.6/site-packages/abusehelper/core/startup.py", line 140, in _launch
2016-04-18 10:18:24Z startup[2824] CRITICAL     path, _ = os.path.split(conf.module)
2016-04-18 10:18:24Z startup[2824] CRITICAL   File "/usr/lib64/python2.6/posixpath.py", line 82, in split
2016-04-18 10:18:24Z startup[2824] CRITICAL     i = p.rfind('/') + 1
2016-04-18 10:18:24Z startup[2824] CRITICAL AttributeError: 'function' object has no attribute 'rfind'
```

Correct way of launching the roomreader bot was found. Nevertheless, as the startupbot crashed in this manner, the rest of the botnet processes were left running even if `botnet` command showed that no bots were running for the botnet. After starting the botnet again, there were two identical botnets running on top of each other based on the PIDs along with their file handles.

**Comment by mseppanen** [comment]
As long as configuration is done using Python code it is almost impossible to prevent user from causing erroneous behaviour with broken configuration file. Closing this for now.
