### ISSUE TITLE
OpenBL Bot Crash

### ISSUE THREAD

**Issue by larihuttunen** [abusesa/abusehelper#63]
```
2016-06-15 21:17:46Z openbl[17092] CRITICAL Traceback (most recent call last):
2016-06-15 21:17:46Z openbl[17092] CRITICAL   File "/usr/lib/python2.6/site-packages/abusehelper/core/bot.py", line 308, in execute
2016-06-15 21:17:46Z openbl[17092] CRITICAL     return self.run()
2016-06-15 21:17:46Z openbl[17092] CRITICAL   File "/usr/lib/python2.6/site-packages/abusehelper/core/bot.py", line 417, in run
2016-06-15 21:17:46Z openbl[17092] CRITICAL     return idiokit.main_loop(throw_stop_on_signal() | self._run())
2016-06-15 21:17:46Z openbl[17092] CRITICAL   File "/usr/lib/python2.6/site-packages/idiokit/idiokit.py", line 352, in _next
2016-06-15 21:17:46Z openbl[17092] CRITICAL     next = require_stream(self._gen.throw(*args))
2016-06-15 21:17:46Z openbl[17092] CRITICAL   File "/usr/lib/python2.6/site-packages/abusehelper/core/bot.py", line 406, in _run
2016-06-15 21:17:46Z openbl[17092] CRITICAL     yield self.lobby.offer(self.bot_name, service)
2016-06-15 21:17:46Z openbl[17092] CRITICAL   File "/usr/lib/python2.6/site-packages/idiokit/idiokit.py", line 352, in _next
2016-06-15 21:17:46Z openbl[17092] CRITICAL     next = require_stream(self._gen.throw(*args))
2016-06-15 21:17:46Z openbl[17092] CRITICAL   File "/usr/lib/python2.6/site-packages/abusehelper/core/services.py", line 229, in offer
2016-06-15 21:17:46Z openbl[17092] CRITICAL     yield self.fork() | service.run()
2016-06-15 21:17:46Z openbl[17092] CRITICAL   File "/usr/lib/python2.6/site-packages/idiokit/idiokit.py", line 352, in _next
2016-06-15 21:17:46Z openbl[17092] CRITICAL     next = require_stream(self._gen.throw(*args))
2016-06-15 21:17:46Z openbl[17092] CRITICAL   File "/usr/lib/python2.6/site-packages/abusehelper/core/services.py", line 307, in run
2016-06-15 21:17:46Z openbl[17092] CRITICAL     state = yield self.errors | self.kill_sessions() | self.main(state)
2016-06-15 21:17:46Z openbl[17092] CRITICAL   File "/usr/lib/python2.6/site-packages/idiokit/idiokit.py", line 352, in _next
2016-06-15 21:17:46Z openbl[17092] CRITICAL     next = require_stream(self._gen.throw(*args))
2016-06-15 21:17:46Z openbl[17092] CRITICAL   File "/usr/lib/python2.6/site-packages/abusehelper/core/bot.py", line 628, in main
2016-06-15 21:17:46Z openbl[17092] CRITICAL     cleanup, arg = yield self._poll_queue.wait()
2016-06-15 21:17:46Z openbl[17092] CRITICAL   File "/usr/lib/python2.6/site-packages/idiokit/idiokit.py", line 352, in _next
2016-06-15 21:17:46Z openbl[17092] CRITICAL     next = require_stream(self._gen.throw(*args))
2016-06-15 21:17:46Z openbl[17092] CRITICAL   File "/usr/lib/python2.6/site-packages/abusehelper/core/utils.py", line 448, in wait
2016-06-15 21:17:46Z openbl[17092] CRITICAL     yield waiter | idiokit.sleep(timeout)
2016-06-15 21:17:46Z openbl[17092] CRITICAL   File "/usr/lib/python2.6/site-packages/idiokit/idiokit.py", line 352, in _next
2016-06-15 21:17:46Z openbl[17092] CRITICAL     next = require_stream(self._gen.throw(*args))
2016-06-15 21:17:46Z openbl[17092] CRITICAL   File "/usr/lib/python2.6/site-packages/abusehelper/core/services.py", line 325, in kill_sessions
2016-06-15 21:17:46Z openbl[17092] CRITICAL     yield idiokit.consume()
2016-06-15 21:17:46Z openbl[17092] CRITICAL   File "/usr/lib/python2.6/site-packages/idiokit/idiokit.py", line 352, in _next
2016-06-15 21:17:46Z openbl[17092] CRITICAL     next = require_stream(self._gen.throw(*args))
2016-06-15 21:17:46Z openbl[17092] CRITICAL   File "/usr/lib/python2.6/site-packages/idiokit/idiokit.py", line 735, in map
2016-06-15 21:17:46Z openbl[17092] CRITICAL     value = yield next()
2016-06-15 21:17:46Z openbl[17092] CRITICAL   File "/usr/lib/python2.6/site-packages/idiokit/idiokit.py", line 352, in _next
2016-06-15 21:17:46Z openbl[17092] CRITICAL     next = require_stream(self._gen.throw(*args))
2016-06-15 21:17:46Z openbl[17092] CRITICAL   File "/usr/lib/python2.6/site-packages/idiokit/idiokit.py", line 735, in map
2016-06-15 21:17:46Z openbl[17092] CRITICAL     value = yield next()
2016-06-15 21:17:46Z openbl[17092] CRITICAL   File "/usr/lib/python2.6/site-packages/abusehelper/core/services.py", line 340, in _guarded
2016-06-15 21:17:46Z openbl[17092] CRITICAL     state = yield session
2016-06-15 21:17:46Z openbl[17092] CRITICAL   File "/usr/lib/python2.6/site-packages/idiokit/idiokit.py", line 354, in _next
2016-06-15 21:17:46Z openbl[17092] CRITICAL     next = require_stream(self._gen.send(peel_args(args)))
2016-06-15 21:17:46Z openbl[17092] CRITICAL   File "/usr/lib/python2.6/site-packages/abusehelper/core/bot.py", line 600, in feed
2016-06-15 21:17:46Z openbl[17092] CRITICAL     yield self.poll(*key) | self.dedup(key)
2016-06-15 21:17:46Z openbl[17092] CRITICAL   File "/usr/lib/python2.6/site-packages/idiokit/idiokit.py", line 352, in _next
2016-06-15 21:17:46Z openbl[17092] CRITICAL     next = require_stream(self._gen.throw(*args))
2016-06-15 21:17:46Z openbl[17092] CRITICAL   File "/usr/lib/python2.6/site-packages/abusehelper/core/bot.py", line 570, in dedup
2016-06-15 21:17:46Z openbl[17092] CRITICAL     event = yield idiokit.next()
2016-06-15 21:17:46Z openbl[17092] CRITICAL   File "/usr/lib/python2.6/site-packages/idiokit/idiokit.py", line 354, in _next
2016-06-15 21:17:46Z openbl[17092] CRITICAL     next = require_stream(self._gen.send(peel_args(args)))
2016-06-15 21:17:46Z openbl[17092] CRITICAL   File "/usr/lib/python2.6/site-packages/abusehelper/bots/openbl/openblbot.py", line 43, in _poll
2016-06-15 21:17:46Z openbl[17092] CRITICAL     ip, time = line.split()
2016-06-15 21:17:46Z openbl[17092] CRITICAL ValueError: need more than 1 value to unpack
```

**Comment by oherrala** [comment]
Fixed in #64
